In [1]:
import torch
from torch.utils.data import Dataset, DataLoader
import os
import numpy as np

from models.data import RandomEpisodes

In [2]:
TRAIN_PATH = 'Episode_Data\Random_Episodes'
new_dataset = RandomEpisodes(TRAIN_PATH)

Loading Episode Data
Finished Loading Episode Data


In [3]:
DL = DataLoader(new_dataset, batch_size=1, shuffle=False, num_workers=1)



In [6]:
for obs, act in DL:
    print(obs[0])

tensor([[-5.5483e-01,  1.9465e+00,  8.0134e-01,  ...,  1.3178e-02,
         -3.9821e-02, -2.7750e-03],
        [-5.5418e-01,  1.9458e+00,  8.0170e-01,  ...,  1.2223e-02,
         -4.5455e-02, -2.7750e-03],
        [-5.5354e-01,  1.9452e+00,  8.0205e-01,  ...,  6.8118e-03,
          5.9619e-02, -2.7750e-03],
        ...,
        [ 4.9944e-01,  6.2004e-01,  3.0661e-02,  ...,  2.5592e-02,
         -1.7507e-03,  0.0000e+00],
        [ 5.0039e-01,  6.2003e-01,  3.0796e-02,  ..., -2.1231e-02,
          7.5121e-03,  0.0000e+00],
        [ 5.0134e-01,  6.2003e-01,  3.0913e-02,  ..., -6.2580e-02,
         -1.3051e-02,  0.0000e+00]])
tensor([[-1.6148e+00,  1.9307e+00,  6.8518e-01,  ..., -3.2942e-01,
          1.2284e-01,  0.0000e+00],
        [-1.6135e+00,  1.9292e+00,  6.8504e-01,  ..., -3.3951e-01,
          1.6383e-01,  0.0000e+00],
        [-1.6122e+00,  1.9277e+00,  6.8487e-01,  ..., -3.0736e-01,
          1.3353e-01,  0.0000e+00],
        ...,
        [-1.5842e+00,  1.3111e+00,  2.6470e-01

In [4]:
means = []
stds = []

for obs, act in DL:
    means.append(torch.mean(torch.abs(obs[0]), 0))
    
print(torch.mean(torch.stack(means), 0))   

tensor([0.9030, 1.1609, 0.1628, 0.5004, 0.5190, 0.4341, 0.4614, 0.4518, 0.5559,
        0.1705, 0.1793, 0.1150, 0.5243, 0.5323, 0.2889, 0.1178, 0.1430, 0.1518,
        0.0964, 0.6976, 0.6949, 0.9102, 1.2457, 1.2364, 1.4500, 0.1806, 0.1759,
        0.4417, 4.8686, 4.9534, 3.7409, 0.0953])


In [5]:
for obs, act in DL:
    print(act[0])
    print(act[0][:, 0:5])

tensor([[ 0.0534,  0.8315,  0.0642,  ...,  0.0000,  1.0000,  0.0000],
        [ 0.2137, -0.2395,  0.1097,  ...,  1.0000,  1.0000,  0.0000],
        [-0.1612,  0.8127,  0.8183,  ...,  1.0000,  0.0000,  0.0000],
        ...,
        [ 0.2732, -0.1212,  0.9545,  ...,  1.0000,  0.0000,  1.0000],
        [ 0.0314,  0.9125, -0.2275,  ...,  0.0000,  0.0000,  1.0000],
        [-0.2291, -0.4350, -0.6226,  ...,  0.0000,  1.0000,  0.0000]])
tensor([[ 0.0534,  0.8315,  0.0642, -0.3421,  0.4672],
        [ 0.2137, -0.2395,  0.1097, -0.1077,  0.5902],
        [-0.1612,  0.8127,  0.8183,  0.4326, -0.4910],
        ...,
        [ 0.2732, -0.1212,  0.9545,  0.1944, -0.5357],
        [ 0.0314,  0.9125, -0.2275, -0.5146, -0.1996],
        [-0.2291, -0.4350, -0.6226,  0.5689, -0.5500]])
tensor([[ 0.1057, -0.2118,  0.6650,  ...,  1.0000,  0.0000,  1.0000],
        [-0.6654, -0.5911,  0.6134,  ...,  0.0000,  0.0000,  0.0000],
        [-0.5695,  0.0359,  0.2337,  ...,  1.0000,  0.0000,  1.0000],
        ...,